name: Coverage Guard

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build and generate coverage for PR branch
        run: |
          mvn clean install
          cp target/site/jacoco/jacoco.xml jacoco_pr.xml

      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref || github.ref }}

      - name: Build and generate coverage for base branch
        run: |
          mvn clean install
          cp target/site/jacoco/jacoco.xml jacoco_base.xml

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Compare coverage and post comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/coverage_comment.py
